CREATE TABLE manage_keys (
    entity_id INT AUTO_INCREMENT PRIMARY KEY,
    api_key TEXT,
    name VARCHAR(255),
    is_active SMALLINT,
    revoked_At TIMESTAMP,
    created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
